### ISSUE TITLE
[Bug] Heroku部署后telegram bot无响应

### ISSUE THREAD

**Issue by Hermittttt** [Astrian/IFS-RSVP-Bot#15]
## Bug 描述
在heroku按照教程部署后，telegram bot的/start无响应。

## Telegram 上下文
无

## 附加信息
无

**Comment by Astrian** [comment]
确认是在初始化启动过程中出现问题报错。

**Comment by Astrian** [comment]
已经在 [0.3.3 版本](https://github.com/Astrian/IFS-RSVP-Bot/releases/tag/v0.3.3) 中修复该问题。
